param(
    [string]$InputPath = (Join-Path $PSScriptRoot '..\jdm (1).sql'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\backend\database\schema\mysql-schema.sql')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $InputPath)) {
    throw "SQL source file not found: $InputPath"
}

$privateTables = @(
    'cart',
    'cart_items',
    'chat_rooms',
    'messages',
    'notifications',
    'orders',
    'order_items',
    'password_resets',
    'payments',
    'personal_access_tokens',
    'recommendation_logs',
    'returns',
    'reviews',
    'review_images',
    'search_histories',
    'sessions',
    'shipments',
    'stock_exports',
    'stock_imports',
    'stock_import_items',
    'support_tickets',
    'users',
    'wishlists'
)

$content = [IO.File]::ReadAllText((Resolve-Path -LiteralPath $InputPath))

foreach ($table in $privateTables) {
    $escapedTable = [Regex]::Escape($table)
    $pattern = "(?ms)^INSERT INTO ``$escapedTable`` .*?;\r?\n"
    $content = [Regex]::Replace($content, $pattern, '')
}

# cPanel shared hosting commonly uses MariaDB, which does not support MySQL 8's
# utf8mb4_0900_ai_ci collation. utf8mb4_unicode_ci works on both platforms.
$content = $content.Replace('utf8mb4_0900_ai_ci', 'utf8mb4_unicode_ci')

$banner = @"
-- JDM WORLD public bootstrap schema
-- Generated by scripts/create-public-sql.ps1.
-- Customer accounts, credentials, OTPs, orders, tokens and user-generated data are intentionally excluded.

"@

$outputDirectory = Split-Path -Parent $OutputPath
[IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[IO.File]::WriteAllText($OutputPath, $banner + $content, [Text.UTF8Encoding]::new($false))

Write-Host "Public schema created: $OutputPath"
